### ISSUE TITLE
Step Re-Grid: Bug: all windows shift instead of being redimensioned.

### ISSUE THREAD

**Issue by jlemonde** [nclarius/KWin-window-positioning-scripts#1]
Dear nclarius,
I've just tried out your freshly published kwin script, whose idea I find gorgeous!

Sadly it doesn't work for me. I believe that in addition to or instead of redimensioning the windows, it moves them (all of them) by some amount, that might be dependent on the user's configured window border width or something (I use Breeze with the official no margins opt-in option).
I hereby join a short video so that you can see. In the video, I cover all four directions, but there is no way to even get the windows back to the left direction... but that's probably linked to the issue mentioned above.

Thanks !!

PS There seem to be issues with Github's video upload; so view it on my nextcloud: https://guadjoma.xyz/index.php/s/gCqCyikXiJRkGqM

**Comment by nclarius** [comment]
Your video file on both sites is broken, but I assume your guess is correct and it has to do with the window borders or tile gaps if you have them, since by default only windows exactly at the screen edge are considered tiled and everything else will be moved. Please see if increasing the tolerance in the configuration, so that windows further away from the screen edges are detected as tiled, solves the problem. (If the configuration button doesn't show or the changes don't apply, see the steps described in the readme.)

**Comment by jlemonde** [comment]
Indeed, increasing the tolerance does the trick. The thing is that I have your other extension "Tile Gaps" enabled as well, so the tiled windows aren't touching the screen edges ever. I increased the tolerance in 'Step Re-Grid' to the same amount as in 'Tile Gaps'. Thanks, your extensions are super nice!

![Capture-2021-11-08-15-20-06](https://user-images.githubusercontent.com/30623792/140758549-1b790d99-33dd-4434-b295-f14d3d386f9b.png) 
![Capture-2021-11-08-15-20-23](https://user-images.githubusercontent.com/30623792/140758551-bd29263d-ebf2-4bf0-857d-a18cd990d04a.png)

PS: weird that I can't upload a video. I can e-mail it to you if you wish, but you may have enough information to reproduce, should you want to!

**Comment by nclarius** [comment]
If you have tile gaps and increasing the tolerance solved the problem, then that certainly was the issue and I no longer need the video. I'll include a note in the readme to make future users aware of it.

Glad to hear it works now! If you're happy with it, you can help spread the word by leaving a review in the KDE store.
