### ISSUE TITLE
Question: what is active screen?

### ISSUE THREAD

**Issue by psifidotos** [nclarius/KWin-window-positioning-scripts#1]
Really nice work!
One question, do you know what is considered an active screen for KWin?
Where the user is writing or the mouse is located or something else?

thank you

**Comment by nclarius** [comment]
Since I have focus follows mouse enabled, it made no difference to me, but good point, I just tried it out.  
What KWin considers the active screen appears to be the one where the cursor is located.  
There seems to be no straightforward way to make the default opening screen the one which has the window that is in focus.

**Comment by nclarius** [comment]
It made no difference to me since I have 'focused follows mouse' enabled, but good point.  
What KWin considers the active screen appears to be the one where the cursor is located.    
I just added another script that will make the default opening window the screen that has the focused window.
